### PR TITLE
Make static linking work in OSX

### PR DESCRIPTION
**Pull request by andrewvmail**
Dont merge yet

### CODE REVIEW

**Comment by davehorton** [comment]
Thanks so much for working this!

**Comment by andrewvmail** [comment]
Hi Dave, I got it building for OSX now but I'm failing your test. 

1. I have to delete all the dylibs because osx compiler defaults to the dylibs [known bug](https://stackoverflow.com/questions/37038472/osx-how-to-statically-link-a-library-and-dynamically-link-the-standard-library?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

2. and it doesnt like the default toolkit boost detects when using the default I get error below. but when i use gcc it works.
```
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost3log11v2_mt_posix4core3getEv
  Referenced from: /Users/momo/projects/drachtio-serverb/drachtio-server/build/./drachtio
  Expected in: flat namespace
```

3. maybe i found unneeded code, on your [make clean ](https://github.com/davehorton/drachtio-server/blob/master/Makefile.am#L53) is bootstrap.sh intended to run?

**Comment by andrewvmail** [comment]
Hey Dave I think we are good for merging, C++ build process is a beast the patience you learn haha.

**Comment by davehorton** [comment]
Thank you so much!

**Pull request merged**
