### PR TITLE
Added library required to build the server

### PR DESCRIPTION
**Pull request by csiwek**

### CODE REVIEW

**Comment by csiwek** [comment]
Fresh installation of Debian 9 . It was failing like this:

**Comment by davehorton** [comment]
Ah ok.  BTW I recommend using the 'develop' branch rather than 'master'.

**Comment by csiwek** [comment]
I did use the develop branch (as per doc in the master) but I guess most of people follow the documentation from Master :-) Do you want me to create also PR for develop?

**Comment by davehorton** [comment]
Sure that would be great

On Sep 5, 2018, at 12:46 PM, Cezary Siwek <notifications@github.com> wrote:

I did use the develop branch (as per doc in the master) but I guess most of people follow the documentation from Master :-) Do you want me to create also PR for develop?

**Pull request merged**
